### ISSUE TITLE
FC with custom database

### ISSUE THREAD

**Issue by 4679** [SimonSchubert/LinuxCommandBibliotheca#1]
I replace the commands.db from the .apk file with the commands.db generate by myself with archlinux
It worked on the commands list,but when i clicked anyone of them,the app has crashed.

Something wrong? Sorry for my bad English. :-)

**Comment by SimonSchubert** [comment]
Hey, sorry I just saw your question. I can't tell you what happend in your project. What did the crashreport say? I kinda have bad news for you because I just replaced the sqlite database with a realm (realm.io) database.

**Comment by 4679** [comment]
Forget it,dude. I gave up.
