### ISSUE TITLE
Search commands by full name

### ISSUE THREAD

**Issue by MarcoWagener** [SimonSchubert/LinuxCommandBibliotheca#2]
Hi there

First off thanx for a great app! One small enchancement. When searching for a command each command's name is "broken up" into the command, e.g. "_exit" and a short description "terminate the calling process". For Linux newbs (like me) it would be greate to search on both the command name and description. Allowing you to search for a term like "terminate" as you might not have a clue as to what the command's name might be.

Regards

**Comment by SimonSchubert** [comment]
Good point, I will have a look into it. Thanks

**Comment by SimonSchubert** [comment]
Feature is implemented :)
